### ISSUE TITLE
Build failure on macOS

### ISSUE THREAD

**Issue by pmoura** [infradig/trealla#167]
Version v1.6.21-54-ga7cab no longer builds on macOS due to the `gmake` attempt to use Apple's distributed version of readline, which comes from *BSD and doesn't provide the same features of GNU readline:

```text
$ gmake clean && gmake NOSSL=1 NOLDLIBS=1
rm -f tpl *.o gmon.* vgcore.* *.core core core.* faultinject.*
cc -Isrc -I/usr/local/include -DVERSION='"v1.6.21-54-ga7cab"' -O3  -Wall -Wextra -D_GNU_SOURCE   -c -o tpl.o tpl.c
cc -Isrc -I/usr/local/include -DVERSION='"v1.6.21-54-ga7cab"' -O3  -Wall -Wextra -D_GNU_SOURCE   -c -o history.o history.c
history.c:87:2: error: implicit declaration of function 'rl_clear_history' is invalid in C99
      [-Werror,-Wimplicit-function-declaration]
        rl_clear_history();
        ^
history.c:87:2: note: did you mean 'clear_history'?
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/readline/history.h:147:8: note: 
      'clear_history' declared here
void             clear_history(void);
                 ^
1 error generated.
gmake: *** [<builtin>: history.o] Error 1
```

This is a common issue when compiling software on macOS, including for other Prolog systems. The usual solution is to use MacPorts or Homebrew to install GNU readline. But that also requires configure/Makefile changes to look for this version installation directories. A temporary fix could be to allow disabling compilation with readline (users can always use `rlwrap tlp` to get some of the benefits).

**Comment by infradig** [comment]
Fixed by disabling rl_clear_history. Not really needed.

**Comment by pmoura** [comment]
Builds fine now on macOS. Thanks for the quick fix.

**Comment by infradig** [comment]
Unrelated, but it came out in the cleanup work... the reason approx equal
is printing it's failure result like 'false=~=false' is because while the
op specifier is set correctly, no arity is attached to the operator and I
wasn't testing for that, so it was grabbing garbage args. Presumably this
is also why the actual test fails. I have fixed this printing. No actual
clue at this stage why this happens.

**Comment by pmoura** [comment]
With that fix for operators, we now get a different error with calls to the `lgtunit::(=~=)/2` predicate. For example:

```text
!     sample_arithmetic_mean_2_02: failure (in 9.2983245849609375e-05 seconds)
!       test assertion throws an error: '=~=' - type_error(callable,51.0)
!       in file /Users/pmoura/logtalk/library/statistics/tests.lgt between lines 50-52
!     sample_geometric_mean_2_02: failure (in 0.00083112716674804688 seconds)
!       test assertion throws an error: '=~=' - type_error(callable,48.769361068905745)
!       in file /Users/pmoura/logtalk/library/statistics/tests.lgt between lines 55-57
!     sample_harmonic_mean_2_02: failure (in 0.00010204315185546875 seconds)
!       test assertion throws an error: '=~=' - type_error(callable,46.694089547712018)
```

The predicate is not declared as a meta-predicate (it expects numbers arguments) and thus it's puzzling from where the `callable` type error is coming from. But this latest fix does result in less broken and crashed test sets. The issue we discussed in the past still persists, however:

```text
?- lgtunit::'=~='(43.9, 43.8).
uncaught exception: error(existence_error(predicate_declaration,'=~='/2),logtalk(lgtunit::'=~='(43.9,43.8),c(user,user,r(user,lgtunit,[],[]))))
false.
```

It seems to be causes by having `=~=` both as an infix operator and a predicate.

**Comment by pmoura** [comment]
Try:

```text
$ tplgt
...
?- {lgtunit(loader)}.
...
?- current_op(P, T, =~=).
false.
?- writeq(lgtunit::assertion(=~=(119.0,119.0))), nl.
lgtunit::assertion('=~=')
true.
```

**Comment by infradig** [comment]
Ok, could the final clue needed...
