### ISSUE TITLE
Odd warnings and errors

### ISSUE THREAD

**Issue by pmoura** [infradig/trealla#176]
Running the tests for the Logtalk `closed_world_assumption` example shows several odd warnings and errors:

```text
Trealla Prolog (c) Infradig 2020, v1.7.23-1-g83b1e
?- {closed_world_assumption(tester)}.
Warning: singleton: [], near line 942, file '/Users/pmoura/logtalk/scratch/core_messages_3972010687_lgt.pl'
*     Declared static predicate called but not defined: shed/0
*       while compiling object house
*       in file /Users/pmoura/logtalk/examples/closed_world_assumption/closed_world_assumption.lgt between lines 13-16
*     
*     Declared static predicate called but not defined: garage/0
*       while compiling object house
*       in file /Users/pmoura/logtalk/examples/closed_world_assumption/closed_world_assumption.lgt between lines 13-16
*     
*     Unknown predicate called but not defined: pool/0
*       while compiling object house
*       in file /Users/pmoura/logtalk/examples/closed_world_assumption/closed_world_assumption.lgt between lines 16-18
*     
% 
% tests started at 2021-03-04, 21:56:49
% 
% running tests from object tests
% file: /Users/pmoura/logtalk/examples/closed_world_assumption/tests.lgt
% 
% closed_world_assumption_01: success (in 4.6968460083007812e-05 seconds)
% closed_world_assumption_02: success (in 2.002716064453125e-05 seconds)
% closed_world_assumption_03: success (in 1.6927719116210938e-05 seconds)
% closed_world_assumption_04: success (in 3.2901763916015625e-05 seconds)
% closed_world_assumption_05: success (in 2.47955322265625e-05 seconds)
Error: syntax error, mismatched parens/brackets/braces, line nbr 1
!     closed_world_assumption_06: failure (in 6.67572021484375e-05 seconds)
!       test goal throws the wrong error:
!         expected error(existence_error(procedure,'$VAR'(0)),'$VAR'(1))
!         but got  error
!       in file /Users/pmoura/logtalk/examples/closed_world_assumption/tests.lgt between lines 21-23
```

The first one is:

```text
Warning: singleton: [], near line 942, file '/Users/pmoura/logtalk/scratch/core_messages_3972010687_lgt.pl'
```

The `core_messages` file is loaded at Logtalk startup. But we only get this (spurious) warning when loading other code.

The second issue is:

```text
Error: syntax error, mismatched parens/brackets/braces, line nbr 1
```

The same code runs fine with other backends. Thus, it seems to be some bug in recent work on parens/brackets/braces balance checking.

The third issue is getting an exception that's just the atom `error`.

**Comment by infradig** [comment]
My guess is that filename is just a left-over and the [] is certainly
spurious. Haven't got to the bottom of that yet but it appeared with the
predicate_property/2 changes.

**Comment by pmoura** [comment]
P.S. Something broke Logtalk loading, at least on macOS, in the latest commits:

```text
$ tpl
Trealla Prolog (c) Infradig 2020, v1.7.23-29-gb3a50
?- ^D

$ tplgt
tpl(40153,0x11e46ce00) malloc: *** error for object 0x7fceb8d04720: pointer being freed was not allocated
tpl(40153,0x11e46ce00) malloc: *** set a breakpoint in malloc_error_break to debug
Abort trap: 6
```

**Comment by infradig** [comment]
I temporarily pushed something like that. Should be fixed now?

**Comment by pmoura** [comment]
Still broken:

```text
$ tpl
Trealla Prolog (c) Infradig 2020, v1.7.24
?- ^D

$ tplgt
tpl(40649,0x1072d5e00) malloc: *** error for object 0x7f87e3c2a990: pointer being freed was not allocated
tpl(40649,0x1072d5e00) malloc: *** set a breakpoint in malloc_error_break to debug
Abort trap: 6
```

**Comment by pmoura** [comment]
The macOS crash persists in v1.7.25. Similar malloc error. Let me know if there's a way for me to provide more information to help diagnose and fix the bug.

**Comment by pmoura** [comment]
v1.7.25-1-g0c568 no longer crashes loading Logtalk on macOS 👍

**Comment by pmoura** [comment]
I no longer get the  singleton warning in the example above but the other two issues are still present.

**Comment by infradig** [comment]
I'll try and get around to looking at it.

**Comment by pmoura** [comment]
All of the `closed_world_assumption` tests no pass and without odd warnings and errors. Thanks for the quick fix!
